/**
 * @fileoverview Auto-generated discovery config for test filtering
 * Generated by test-runner.js - do not edit manually
 */

export const testRunnerConfig = {
  includeAllEndpoints: false,
  includedApis: ["wsdot-highway-cameras"],
  excludedApis: [],
  excludedEndpoints: [],
  validateEndpoints: true,
  enableDebugOutput: false,
  generateAllConfigs: false,
  configGenerationApis: ["wsdot-highway-cameras"],
};
