/**
 * @fileoverview Auto-generated discovery config for test filtering
 * Generated by test-runner.js - do not edit manually
 */

module.exports = {
  testRunnerConfig: {
    includeAllEndpoints: false,
    includedApis: ["wsdot-traffic-flow"],
    excludedApis: [],
    excludedEndpoints: [],
    validateEndpoints: true,
    enableDebugOutput: false,
    generateAllConfigs: false,
    configGenerationApis: ["wsdot-traffic-flow"],
  }
};
