import { resolve } from "node:path";
import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts", 
    "src/cli/fetch-dottie.ts",
    // Add API-specific entry points
    "src/apis/wsf-vessels/index.ts",
    "src/apis/wsf-vessels/core.ts",
    "src/apis/wsf-vessels/hooks.ts",
    "src/apis/wsdot-border-crossings/index.ts",
    "src/apis/wsdot-border-crossings/core.ts",
    "src/apis/wsdot-border-crossings/hooks.ts",
    "src/apis/wsdot-bridge-clearances/index.ts",
    "src/apis/wsdot-bridge-clearances/core.ts",
    "src/apis/wsdot-bridge-clearances/hooks.ts",
    "src/apis/wsdot-commercial-vehicle-restrictions/index.ts",
    "src/apis/wsdot-commercial-vehicle-restrictions/core.ts",
    "src/apis/wsdot-commercial-vehicle-restrictions/hooks.ts",
    "src/apis/wsdot-highway-alerts/index.ts",
    "src/apis/wsdot-highway-alerts/core.ts",
    "src/apis/wsdot-highway-alerts/hooks.ts",
    "src/apis/wsdot-highway-cameras/index.ts",
    "src/apis/wsdot-highway-cameras/core.ts",
    "src/apis/wsdot-highway-cameras/hooks.ts",
    "src/apis/wsdot-mountain-pass-conditions/index.ts",
    "src/apis/wsdot-mountain-pass-conditions/core.ts",
    "src/apis/wsdot-mountain-pass-conditions/hooks.ts",
    "src/apis/wsdot-toll-rates/index.ts",
    "src/apis/wsdot-toll-rates/core.ts",
    "src/apis/wsdot-toll-rates/hooks.ts",
    "src/apis/wsdot-traffic-flow/index.ts",
    "src/apis/wsdot-traffic-flow/core.ts",
    "src/apis/wsdot-traffic-flow/hooks.ts",
    "src/apis/wsdot-travel-times/index.ts",
    "src/apis/wsdot-travel-times/core.ts",
    "src/apis/wsdot-travel-times/hooks.ts",
    "src/apis/wsdot-weather-information/index.ts",
    "src/apis/wsdot-weather-information/core.ts",
    "src/apis/wsdot-weather-information/hooks.ts",
    "src/apis/wsdot-weather-readings/index.ts",
    "src/apis/wsdot-weather-readings/core.ts",
    "src/apis/wsdot-weather-readings/hooks.ts",
    "src/apis/wsdot-weather-stations/index.ts",
    "src/apis/wsdot-weather-stations/core.ts",
    "src/apis/wsdot-weather-stations/hooks.ts",
    "src/apis/wsf-fares/index.ts",
    "src/apis/wsf-fares/core.ts",
    "src/apis/wsf-fares/hooks.ts",
    "src/apis/wsf-schedule/index.ts",
    "src/apis/wsf-schedule/core.ts",
    "src/apis/wsf-schedule/hooks.ts",
    "src/apis/wsf-terminals/index.ts",
    "src/apis/wsf-terminals/core.ts",
    "src/apis/wsf-terminals/hooks.ts",
  ],
  format: ["esm", "cjs"], // Build both ESM and CJS formats
  dts: {
    entry: [
      "src/index.ts", 
      // Add API-specific type definition entries
      "src/apis/wsf-vessels/index.ts",
      "src/apis/wsf-vessels/core.ts",
      "src/apis/wsf-vessels/hooks.ts",
      "src/apis/wsdot-border-crossings/index.ts",
      "src/apis/wsdot-border-crossings/core.ts",
      "src/apis/wsdot-border-crossings/hooks.ts",
      "src/apis/wsdot-bridge-clearances/index.ts",
      "src/apis/wsdot-bridge-clearances/core.ts",
      "src/apis/wsdot-bridge-clearances/hooks.ts",
      "src/apis/wsdot-commercial-vehicle-restrictions/index.ts",
      "src/apis/wsdot-commercial-vehicle-restrictions/core.ts",
      "src/apis/wsdot-commercial-vehicle-restrictions/hooks.ts",
      "src/apis/wsdot-highway-alerts/index.ts",
      "src/apis/wsdot-highway-alerts/core.ts",
      "src/apis/wsdot-highway-alerts/hooks.ts",
      "src/apis/wsdot-highway-cameras/index.ts",
      "src/apis/wsdot-highway-cameras/core.ts",
      "src/apis/wsdot-highway-cameras/hooks.ts",
      "src/apis/wsdot-mountain-pass-conditions/index.ts",
      "src/apis/wsdot-mountain-pass-conditions/core.ts",
      "src/apis/wsdot-mountain-pass-conditions/hooks.ts",
      "src/apis/wsdot-toll-rates/index.ts",
      "src/apis/wsdot-toll-rates/core.ts",
      "src/apis/wsdot-toll-rates/hooks.ts",
      "src/apis/wsdot-traffic-flow/index.ts",
      "src/apis/wsdot-traffic-flow/core.ts",
      "src/apis/wsdot-traffic-flow/hooks.ts",
      "src/apis/wsdot-travel-times/index.ts",
      "src/apis/wsdot-travel-times/core.ts",
      "src/apis/wsdot-travel-times/hooks.ts",
      "src/apis/wsdot-weather-information/index.ts",
      "src/apis/wsdot-weather-information/core.ts",
      "src/apis/wsdot-weather-information/hooks.ts",
      "src/apis/wsdot-weather-readings/index.ts",
      "src/apis/wsdot-weather-readings/core.ts",
      "src/apis/wsdot-weather-readings/hooks.ts",
      "src/apis/wsdot-weather-stations/index.ts",
      "src/apis/wsdot-weather-stations/core.ts",
      "src/apis/wsdot-weather-stations/hooks.ts",
      "src/apis/wsf-fares/index.ts",
      "src/apis/wsf-fares/core.ts",
      "src/apis/wsf-fares/hooks.ts",
      "src/apis/wsf-schedule/index.ts",
      "src/apis/wsf-schedule/core.ts",
      "src/apis/wsf-schedule/hooks.ts",
      "src/apis/wsf-terminals/index.ts",
      "src/apis/wsf-terminals/core.ts",
      "src/apis/wsf-terminals/hooks.ts",
    ], // Generate .d.ts files for main library and API entries
  },
  splitting: true,
  sourcemap: true,
  clean: false,
  minify: true,
  external: [
    "react",
    "react-dom",
    "@tanstack/react-query",
    "@tanstack/query-core",
    // CLI dependencies - exclude from main bundle
    "commander",
    "chalk",
  ],
  outDir: "dist",
  outExtension({ format }) {
    return {
      js: format === "esm" ? ".mjs" : ".js", // Use .mjs for ESM, .js for CJS
    };
  },
  treeshake: true,
  // Ensure proper type exports
  noExternal: [],
  // Configure path aliases
  esbuildOptions(options) {
    options.alias = {
      "@": resolve(__dirname, "src"),
    };
    return options;
  },
});
