import { createApiDefinition } from "../utils";
import {
  cacheFlushDateInputSchema,
  terminalBasicsByIdInputSchema,
  terminalBasicsInputSchema,
  terminalBulletinsByIdInputSchema,
  terminalBulletinsInputSchema,
  terminalLocationsByIdInputSchema,
  terminalLocationsInputSchema,
  terminalSailingSpaceByIdInputSchema,
  terminalSailingSpaceInputSchema,
  terminalTransportsByIdInputSchema,
  terminalTransportsInputSchema,
  terminalVerboseByIdInputSchema,
  terminalVerboseInputSchema,
  terminalWaitTimesByIdInputSchema,
  terminalWaitTimesInputSchema,
} from "./original/inputSchemas.original";
import {
  cacheFlushDateSchema,
  terminalBasicDetailsListSchema,
  terminalBasicSchema,
  terminalBulletinSchema,
  terminalBulletinsListSchema,
  terminalLocationSchema,
  terminalLocationsListSchema,
  terminalSailingSpaceSchema,
  terminalSailingSpacesListSchema,
  terminalTransportationOptionSchema,
  terminalTransportationOptionsListSchema,
  terminalVerboseDetailsListSchema,
  terminalVerboseSchema,
  terminalWaitTimeSchema,
  terminalWaitTimesListSchema,
} from "./original/outputSchemas.original";

export const wsfTerminalsApi = createApiDefinition("wsf-terminals", [
  {
    function: "cacheFlushDate",
    endpoint: "/ferries/api/terminals/rest/cacheflushdate",
    inputSchema: cacheFlushDateInputSchema,
    outputSchema: cacheFlushDateSchema,
    sampleParams: {},
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalBasics",
    endpoint: "/ferries/api/terminals/rest/terminalbasics",
    inputSchema: terminalBasicsInputSchema,
    outputSchema: terminalBasicDetailsListSchema,
    sampleParams: {},
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalBasicsByTerminalId",
    endpoint: "/ferries/api/terminals/rest/terminalbasics/{TerminalID}",
    inputSchema: terminalBasicsByIdInputSchema,
    outputSchema: terminalBasicSchema,
    sampleParams: { TerminalID: 1 },
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalBulletins",
    endpoint: "/ferries/api/terminals/rest/terminalbulletins",
    inputSchema: terminalBulletinsInputSchema,
    outputSchema: terminalBulletinsListSchema,
    sampleParams: {},
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalBulletinsByTerminalId",
    endpoint: "/ferries/api/terminals/rest/terminalbulletins/{TerminalID}",
    inputSchema: terminalBulletinsByIdInputSchema,
    outputSchema: terminalBulletinSchema,
    sampleParams: { TerminalID: 1 },
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalLocations",
    endpoint: "/ferries/api/terminals/rest/terminallocations",
    inputSchema: terminalLocationsInputSchema,
    outputSchema: terminalLocationsListSchema,
    sampleParams: {},
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalLocationsByTerminalId",
    endpoint: "/ferries/api/terminals/rest/terminallocations/{TerminalID}",
    inputSchema: terminalLocationsByIdInputSchema,
    outputSchema: terminalLocationSchema,
    sampleParams: { TerminalID: 1 },
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalSailingSpace",
    endpoint: "/ferries/api/terminals/rest/terminalsailingspace",
    inputSchema: terminalSailingSpaceInputSchema,
    outputSchema: terminalSailingSpacesListSchema,
    sampleParams: {},
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalSailingSpaceByTerminalId",
    endpoint: "/ferries/api/terminals/rest/terminalsailingspace/{TerminalID}",
    inputSchema: terminalSailingSpaceByIdInputSchema,
    outputSchema: terminalSailingSpaceSchema,
    sampleParams: { TerminalID: 1 },
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalTransports",
    endpoint: "/ferries/api/terminals/rest/terminaltransports",
    inputSchema: terminalTransportsInputSchema,
    outputSchema: terminalTransportationOptionsListSchema,
    sampleParams: {},
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalTransportsByTerminalId",
    endpoint: "/ferries/api/terminals/rest/terminaltransports/{TerminalID}",
    inputSchema: terminalTransportsByIdInputSchema,
    outputSchema: terminalTransportationOptionSchema,
    sampleParams: { TerminalID: 1 },
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalVerbose",
    endpoint: "/ferries/api/terminals/rest/terminalverbose",
    inputSchema: terminalVerboseInputSchema,
    outputSchema: terminalVerboseDetailsListSchema,
    sampleParams: {},
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalVerboseByTerminalId",
    endpoint: "/ferries/api/terminals/rest/terminalverbose/{TerminalID}",
    inputSchema: terminalVerboseByIdInputSchema,
    outputSchema: terminalVerboseSchema,
    sampleParams: { TerminalID: 1 },
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalWaitTimes",
    endpoint: "/ferries/api/terminals/rest/terminalwaittimes",
    inputSchema: terminalWaitTimesInputSchema,
    outputSchema: terminalWaitTimesListSchema,
    sampleParams: {},
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalWaitTimesByTerminalId",
    endpoint: "/ferries/api/terminals/rest/terminalwaittimes/{TerminalID}",
    inputSchema: terminalWaitTimesByIdInputSchema,
    outputSchema: terminalWaitTimeSchema,
    sampleParams: { TerminalID: 1 },
    cacheStrategy: "STATIC",
  },
]);
