import type { ApiDefinition } from "@/apis/types";
import { input, output } from "./schemas";

export const wsfTerminalsApi: ApiDefinition = {
  name: "wsf-terminals",
  baseUrl: "https://www.wsdot.wa.gov/ferries/api/terminals/rest",
  endpoints: [
    {
      function: "cacheFlushDate",
      endpoint: "/cacheflushdate",
      inputSchema: input.cacheFlushDateSchema,
      outputSchema: output.cacheFlushDateSchema,
      sampleParams: {},
      cacheStrategy: "STATIC",
    },
    {
      function: "terminalBasics",
      endpoint: "/terminalBasics",
      inputSchema: input.terminalBasicsSchema,
      outputSchema: output.terminalBasicDetailsListSchema,
      sampleParams: {},
      cacheStrategy: "STATIC",
    },
    {
      function: "terminalBasicsByTerminalId",
      endpoint: "/terminalBasics/{TerminalID}",
      inputSchema: input.terminalBasicsByIdSchema,
      outputSchema: output.terminalBasicSchema,
      sampleParams: { TerminalID: 1 },
      cacheStrategy: "STATIC",
    },
    {
      function: "terminalBulletins",
      endpoint: "/terminalBulletins",
      inputSchema: input.terminalBulletinsSchema,
      outputSchema: output.terminalBulletinsListSchema,
      sampleParams: {},
      cacheStrategy: "STATIC",
    },
    {
      function: "terminalBulletinsByTerminalId",
      endpoint: "/terminalBulletins/{TerminalID}",
      inputSchema: input.terminalBulletinsByIdSchema,
      outputSchema: output.terminalBulletinSchema,
      sampleParams: { TerminalID: 3 },
      cacheStrategy: "STATIC",
    },
    {
      function: "terminalLocations",
      endpoint: "/terminalLocations",
      inputSchema: input.terminalLocationsSchema,
      outputSchema: output.terminalLocationsListSchema,
      sampleParams: {},
      cacheStrategy: "STATIC",
    },
    {
      function: "terminalLocationsByTerminalId",
      endpoint: "/terminalLocations/{TerminalID}",
      inputSchema: input.terminalLocationsByIdSchema,
      outputSchema: output.terminalLocationSchema,
      sampleParams: { TerminalID: 5 },
      cacheStrategy: "STATIC",
    },
    {
      function: "terminalSailingSpace",
      endpoint: "/terminalSailingSpace",
      inputSchema: input.terminalSailingSpaceSchema,
      outputSchema: output.terminalSailingSpacesListSchema,
      sampleParams: {},
      cacheStrategy: "STATIC",
    },
    {
      function: "terminalSailingSpaceByTerminalId",
      endpoint: "/terminalSailingSpace/{TerminalID}",
      inputSchema: input.terminalSailingSpaceByIdSchema,
      outputSchema: output.terminalSailingSpaceSchema,
      sampleParams: { TerminalID: 7 },
      cacheStrategy: "STATIC",
    },
    {
      function: "terminalTransports",
      endpoint: "/terminalTransports",
      inputSchema: input.terminalTransportsSchema,
      outputSchema: output.terminalTransportationOptionsListSchema,
      sampleParams: {},
      cacheStrategy: "STATIC",
    },
    {
      function: "terminalTransportsByTerminalId",
      endpoint: "/terminalTransports/{TerminalID}",
      inputSchema: input.terminalTransportsByIdSchema,
      outputSchema: output.terminalTransportationOptionSchema,
      sampleParams: { TerminalID: 10 },
      cacheStrategy: "STATIC",
    },
    {
      function: "terminalVerbose",
      endpoint: "/terminalVerbose",
      inputSchema: input.terminalVerboseSchema,
      outputSchema: output.terminalVerboseListSchema,
      sampleParams: {},
      cacheStrategy: "STATIC",
    },
    {
      function: "terminalVerboseByTerminalId",
      endpoint: "/terminalVerbose/{TerminalID}",
      inputSchema: input.terminalVerboseByIdSchema,
      outputSchema: output.terminalVerboseListSchema,
      sampleParams: { TerminalID: 4 },
      cacheStrategy: "STATIC",
    },
    {
      function: "terminalWaitTimes",
      endpoint: "/terminalWaitTimes",
      inputSchema: input.terminalWaitTimesSchema,
      outputSchema: output.terminalWaitTimesListSchema,
      sampleParams: {},
      cacheStrategy: "STATIC",
    },
    {
      function: "terminalWaitTimesByTerminalId",
      endpoint: "/terminalWaitTimes/{TerminalID}",
      inputSchema: input.terminalWaitTimesByIdSchema,
      outputSchema: output.terminalWaitTimeSchema,
      sampleParams: { TerminalID: 11 },
      cacheStrategy: "STATIC",
    },
  ],
};
