import { createApiDefinition } from "../utils";
import { input, output } from "./schemas";

export const wsfTerminalsApi = createApiDefinition("wsf-terminals", [
  {
    function: "cacheFlushDate",
    endpoint: "/ferries/api/terminals/rest/cacheflushdate",
    inputSchema: input.cacheFlushDateSchema,
    outputSchema: output.cacheFlushDateSchema,
    sampleParams: {},
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalBasics",
    endpoint: "/ferries/api/terminals/rest/terminalbasics",
    inputSchema: input.terminalBasicsSchema,
    outputSchema: output.terminalBasicDetailsListSchema,
    sampleParams: {},
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalBasicsByTerminalId",
    endpoint: "/ferries/api/terminals/rest/terminalbasics/{TerminalID}",
    inputSchema: input.terminalBasicsByIdSchema,
    outputSchema: output.terminalBasicSchema,
    sampleParams: { TerminalID: 1 },
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalBulletins",
    endpoint: "/ferries/api/terminals/rest/terminalbulletins",
    inputSchema: input.terminalBulletinsSchema,
    outputSchema: output.terminalBulletinsListSchema,
    sampleParams: {},
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalBulletinsByTerminalId",
    endpoint: "/ferries/api/terminals/rest/terminalbulletins/{TerminalID}",
    inputSchema: input.terminalBulletinsByIdSchema,
    outputSchema: output.terminalBulletinSchema,
    sampleParams: { TerminalID: 3 },
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalLocations",
    endpoint: "/ferries/api/terminals/rest/terminallocations",
    inputSchema: input.terminalLocationsSchema,
    outputSchema: output.terminalLocationsListSchema,
    sampleParams: {},
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalLocationsByTerminalId",
    endpoint: "/ferries/api/terminals/rest/terminallocations/{TerminalID}",
    inputSchema: input.terminalLocationsByIdSchema,
    outputSchema: output.terminalLocationSchema,
    sampleParams: { TerminalID: 5 },
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalSailingSpace",
    endpoint: "/ferries/api/terminals/rest/terminalsailingspace",
    inputSchema: input.terminalSailingSpaceSchema,
    outputSchema: output.terminalSailingSpacesListSchema,
    sampleParams: {},
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalSailingSpaceByTerminalId",
    endpoint: "/ferries/api/terminals/rest/terminalsailingspace/{TerminalID}",
    inputSchema: input.terminalSailingSpaceByIdSchema,
    outputSchema: output.terminalSailingSpaceSchema,
    sampleParams: { TerminalID: 7 },
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalTransports",
    endpoint: "/ferries/api/terminals/rest/terminaltransports",
    inputSchema: input.terminalTransportsSchema,
    outputSchema: output.terminalTransportationOptionsListSchema,
    sampleParams: {},
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalTransportsByTerminalId",
    endpoint: "/ferries/api/terminals/rest/terminaltransports/{TerminalID}",
    inputSchema: input.terminalTransportsByIdSchema,
    outputSchema: output.terminalTransportationOptionSchema,
    sampleParams: { TerminalID: 10 },
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalVerbose",
    endpoint: "/ferries/api/terminals/rest/terminalverbose",
    inputSchema: input.terminalVerboseSchema,
    outputSchema: output.terminalVerboseListSchema,
    sampleParams: {},
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalVerboseByTerminalId",
    endpoint: "/ferries/api/terminals/rest/terminalverbose/{TerminalID}",
    inputSchema: input.terminalVerboseByIdSchema,
    outputSchema: output.terminalVerboseListSchema,
    sampleParams: { TerminalID: 4 },
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalWaitTimes",
    endpoint: "/ferries/api/terminals/rest/terminalwaittimes",
    inputSchema: input.terminalWaitTimesSchema,
    outputSchema: output.terminalWaitTimesListSchema,
    sampleParams: {},
    cacheStrategy: "STATIC",
  },
  {
    function: "terminalWaitTimesByTerminalId",
    endpoint: "/ferries/api/terminals/rest/terminalwaittimes/{TerminalID}",
    inputSchema: input.terminalWaitTimesByIdSchema,
    outputSchema: output.terminalWaitTimeSchema,
    sampleParams: { TerminalID: 11 },
    cacheStrategy: "STATIC",
  },
]);
