import type { ApiDefinition } from "@/shared/endpoints";
import { datesHelper } from "@/shared/utils";
import { input, output } from "./schemas";

export const wsfVesselsApi: ApiDefinition = {
  name: "wsf-vessels",
  baseUrl: "http://www.wsdot.wa.gov/ferries/api/vessels/rest",
  endpoints: [
    {
      function: "cacheFlushDate",
      endpoint: "/cacheflushdate",
      inputSchema: input.cacheFlushDateSchema,
      outputSchema: output.cacheFlushDateSchema,
      sampleParams: {},
      cacheStrategy: "STATIC",
    },
    {
      function: "vesselAccommodations",
      endpoint: "/vesselAccommodations",
      inputSchema: input.vesselAccommodationsSchema,
      outputSchema: output.vesselAccommodationsListSchema,
      sampleParams: {},
      cacheStrategy: "STATIC",
    },
    {
      function: "vesselAccommodationsById",
      endpoint: "/vesselAccommodations/{VesselID}",
      inputSchema: input.vesselAccommodationsByIdSchema,
      outputSchema: output.vesselAccommodationsSchema,
      sampleParams: { VesselID: 65 },
      cacheStrategy: "STATIC",
    },
    {
      function: "vesselBasics",
      endpoint: "/vesselBasics",
      inputSchema: input.vesselBasicsSchema,
      outputSchema: output.vesselBasicDetailsListSchema,
      sampleParams: {},
      cacheStrategy: "STATIC",
    },
    {
      function: "vesselBasicsById",
      endpoint: "/vesselBasics/{VesselID}",
      inputSchema: input.vesselBasicsByIdSchema,
      outputSchema: output.vesselBasicSchema,
      sampleParams: { VesselID: 15 },
      cacheStrategy: "STATIC",
    },
    {
      function: "vesselHistories",
      endpoint: "/vesselHistory",
      inputSchema: input.getAllVesselHistorySchema,
      outputSchema: output.vesselHistoryResponseListSchema,
      sampleParams: {},
      cacheStrategy: "STATIC",
    },
    {
      function: "vesselHistoriesByVesselAndDateRange",
      endpoint: "/vesselHistory/{VesselName}/{DateStart}/{DateEnd}",
      inputSchema: input.getVesselHistorySchema,
      outputSchema: output.vesselHistoryResponseListSchema,
      sampleParams: {
        VesselName: "Cathlamet",
        DateStart: datesHelper.startOfMonth(),
        DateEnd: datesHelper.endOfMonth(),
      },
      cacheStrategy: "STATIC",
    },
    {
      function: "vesselLocations",
      endpoint: "/vesselLocations",
      inputSchema: input.vesselLocationsSchema,
      outputSchema: output.vesselLocationsListSchema,
      sampleParams: {},
      cacheStrategy: "REALTIME",
    },
    {
      function: "vesselLocationsById",
      endpoint: "/vesselLocations/{VesselID}",
      inputSchema: input.vesselLocationsByIdSchema,
      outputSchema: output.vesselLocationsSchema,
      sampleParams: { VesselID: 18 },
      cacheStrategy: "REALTIME",
    },
    {
      function: "vesselStats",
      endpoint: "/vesselStats",
      inputSchema: input.vesselStatsSchema,
      outputSchema: output.vesselStatsListSchema,
      sampleParams: {},
      cacheStrategy: "STATIC",
    },
    {
      function: "vesselStatsById",
      endpoint: "/vesselStats/{VesselID}",
      inputSchema: input.vesselStatsByIdSchema,
      outputSchema: output.vesselStatsSchema,
      sampleParams: { VesselID: 32 },
      cacheStrategy: "STATIC",
    },
    {
      function: "vesselsVerbose",
      endpoint: "/vesselVerbose",
      inputSchema: input.vesselVerboseSchema,
      outputSchema: output.vesselVerboseDetailsListSchema,
      sampleParams: {},
      cacheStrategy: "STATIC",
    },
    {
      function: "vesselsVerboseById",
      endpoint: "/vesselVerbose/{VesselID}",
      inputSchema: input.vesselVerboseByIdSchema,
      outputSchema: output.vesselVerboseSchema,
      sampleParams: { VesselID: 68 },
      cacheStrategy: "STATIC",
    },
  ],
};
