/**
 * @fileoverview Auto-generated test configuration for Wsdot Traffic Flow API
 *
 * This file is automatically generated from discovered Endpoint objects.
 * Do not edit manually - changes will be overwritten.
 */

import type { Endpoint } from "@/shared/endpoints";
import { fetchWithZod } from "@/shared/fetching";
import type { EndpointTestConfig } from "../generators/configGenerator";

// Import the actual endpoint definitions
import * as wsdot_traffic_flow from "@/clients/wsdot-traffic-flow";

/**
 * Auto-generated test configuration for getTrafficFlow endpoint
 */
export const getTrafficFlowConfig: EndpointTestConfig<any, any> = {
  apiFunction: (params: any) => fetchWithZod(wsdot_traffic_flow.getTrafficFlow, params),
  inputSchema: wsdot_traffic_flow.getTrafficFlow.inputSchema,
  outputSchema: wsdot_traffic_flow.getTrafficFlow.outputSchema,
  validParams: wsdot_traffic_flow.getTrafficFlow.sampleParams || {},
  invalidParams: [
    {},
    { invalidField: "invalidValue" },
  ],
  endpointName: "getTrafficFlow",
  category: "data-retrieval",
  maxResponseTime: 10000,
  customTests: [
    {
      name: "Cache Strategy Validation",
      params: wsdot_traffic_flow.getTrafficFlow.sampleParams || {},
      expectation: "success",
      description: "Validates that MINUTE_UPDATES caching works correctly",
    },
    {
      name: "Sample Parameters Test",
      params: wsdot_traffic_flow.getTrafficFlow.sampleParams || {},
      expectation: "success",
      description: "Tests with the provided sample parameters",
    },
  ],
  endpointDefinition: wsdot_traffic_flow.getTrafficFlow,
};

/**
 * Auto-generated test configuration for getTrafficFlowById endpoint
 */
export const getTrafficFlowByIdConfig: EndpointTestConfig<any, any> = {
  apiFunction: (params: any) => fetchWithZod(wsdot_traffic_flow.getTrafficFlowById, params),
  inputSchema: wsdot_traffic_flow.getTrafficFlowById.inputSchema,
  outputSchema: wsdot_traffic_flow.getTrafficFlowById.outputSchema,
  validParams: wsdot_traffic_flow.getTrafficFlowById.sampleParams || {},
  invalidParams: [
    {},
    { invalidField: "invalidValue" },
  ],
  endpointName: "getTrafficFlowById",
  category: "data-retrieval",
  maxResponseTime: 10000,
  customTests: [
    {
      name: "Cache Strategy Validation",
      params: wsdot_traffic_flow.getTrafficFlowById.sampleParams || {},
      expectation: "success",
      description: "Validates that MINUTE_UPDATES caching works correctly",
    },
    {
      name: "Sample Parameters Test",
      params: wsdot_traffic_flow.getTrafficFlowById.sampleParams || {},
      expectation: "success",
      description: "Tests with the provided sample parameters",
    },
  ],
  endpointDefinition: wsdot_traffic_flow.getTrafficFlowById,
};

/**
 * All endpoint configurations for this API
 */
export const wsdot_traffic_flowConfigs = [
  getTrafficFlowConfig,
  getTrafficFlowByIdConfig,
];

/**
 * API module configuration
 */
export const wsdot_traffic_flowModuleConfig = {
  moduleName: "Wsdot Traffic Flow",
  endpoints: wsdot_traffic_flowConfigs,
  settings: {
    baseTimeout: 30000,
    requiresAuth: false,
    rateLimit: {
      requestsPerSecond: 10,
      burstLimit: 50,
    },
    testCategories: ["data-retrieval","validation","performance"],
  },
};
