/**
 * @fileoverview Auto-generated test configuration for Wsdot Highway Cameras API
 *
 * This file is automatically generated from discovered Endpoint objects.
 * Do not edit manually - changes will be overwritten.
 */

import type { Endpoint } from "@/shared/endpoints";
import { fetchWithZod } from "@/shared/fetching";
import type { EndpointTestConfig } from "../generators/configGenerator";

// Import the actual endpoint definitions
import * as wsdot_highway_cameras from "@/clients/wsdot-highway-cameras";

/**
 * Auto-generated test configuration for getHighwayCamera endpoint
 */
export const getHighwayCameraConfig: EndpointTestConfig<any, any> = {
  apiFunction: (params: any) => fetchWithZod(wsdot_highway_cameras.getHighwayCamera, params),
  inputSchema: wsdot_highway_cameras.getHighwayCamera.inputSchema,
  outputSchema: wsdot_highway_cameras.getHighwayCamera.outputSchema,
  validParams: wsdot_highway_cameras.getHighwayCamera.sampleParams || {},
  invalidParams: [
    {},
    { invalidField: "invalidValue" },
  ],
  endpointName: "getHighwayCamera",
  category: "data-retrieval",
  maxResponseTime: 120000,
  customTests: [
    {
      name: "Cache Strategy Validation",
      params: wsdot_highway_cameras.getHighwayCamera.sampleParams || {},
      expectation: "success",
      description: "Validates that DAILY_STATIC caching works correctly",
    },
    {
      name: "Sample Parameters Test",
      params: wsdot_highway_cameras.getHighwayCamera.sampleParams || {},
      expectation: "success",
      description: "Tests with the provided sample parameters",
    },
  ],
  endpointDefinition: wsdot_highway_cameras.getHighwayCamera,
};

/**
 * Auto-generated test configuration for getHighwayCameras endpoint
 */
export const getHighwayCamerasConfig: EndpointTestConfig<any, any> = {
  apiFunction: (params: any) => fetchWithZod(wsdot_highway_cameras.getHighwayCameras, params),
  inputSchema: wsdot_highway_cameras.getHighwayCameras.inputSchema,
  outputSchema: wsdot_highway_cameras.getHighwayCameras.outputSchema,
  validParams: wsdot_highway_cameras.getHighwayCameras.sampleParams || {},
  invalidParams: [
    {},
    { invalidField: "invalidValue" },
  ],
  endpointName: "getHighwayCameras",
  category: "data-retrieval",
  maxResponseTime: 120000,
  customTests: [
    {
      name: "Cache Strategy Validation",
      params: wsdot_highway_cameras.getHighwayCameras.sampleParams || {},
      expectation: "success",
      description: "Validates that DAILY_STATIC caching works correctly",
    },
    {
      name: "Sample Parameters Test",
      params: wsdot_highway_cameras.getHighwayCameras.sampleParams || {},
      expectation: "success",
      description: "Tests with the provided sample parameters",
    },
  ],
  endpointDefinition: wsdot_highway_cameras.getHighwayCameras,
};

/**
 * Auto-generated test configuration for searchHighwayCameras endpoint
 */
export const searchHighwayCamerasConfig: EndpointTestConfig<any, any> = {
  apiFunction: (params: any) => fetchWithZod(wsdot_highway_cameras.searchHighwayCameras, params),
  inputSchema: wsdot_highway_cameras.searchHighwayCameras.inputSchema,
  outputSchema: wsdot_highway_cameras.searchHighwayCameras.outputSchema,
  validParams: wsdot_highway_cameras.searchHighwayCameras.sampleParams || {},
  invalidParams: [
    {},
    { invalidField: "invalidValue" },
  ],
  endpointName: "searchHighwayCameras",
  category: "search",
  maxResponseTime: 120000,
  customTests: [
    {
      name: "Cache Strategy Validation",
      params: wsdot_highway_cameras.searchHighwayCameras.sampleParams || {},
      expectation: "success",
      description: "Validates that DAILY_STATIC caching works correctly",
    },
    {
      name: "Sample Parameters Test",
      params: wsdot_highway_cameras.searchHighwayCameras.sampleParams || {},
      expectation: "success",
      description: "Tests with the provided sample parameters",
    },
  ],
  endpointDefinition: wsdot_highway_cameras.searchHighwayCameras,
};

/**
 * All endpoint configurations for this API
 */
export const wsdot_highway_camerasConfigs = [
  getHighwayCameraConfig,
  getHighwayCamerasConfig,
  searchHighwayCamerasConfig,
];

/**
 * API module configuration
 */
export const wsdot_highway_camerasModuleConfig = {
  moduleName: "Wsdot Highway Cameras",
  endpoints: wsdot_highway_camerasConfigs,
  settings: {
    baseTimeout: 30000,
    requiresAuth: false,
    rateLimit: {
      requestsPerSecond: 10,
      burstLimit: 50,
    },
    testCategories: ["data-retrieval","validation","performance"],
  },
};
