/**
 * @fileoverview Auto-generated test configuration for Wsdot Bridge Clearances API
 *
 * This file is automatically generated from discovered Endpoint objects.
 * Do not edit manually - changes will be overwritten.
 */

import type { Endpoint } from "@/shared/endpoints";
import { fetchWithZod } from "@/shared/fetching";
import type { EndpointTestConfig } from "../generators/configGenerator";

// Import the actual endpoint definitions
import * as wsdot_bridge_clearances from "@/clients/wsdot-bridge-clearances";

/**
 * Auto-generated test configuration for getBridgeClearances endpoint
 */
export const getBridgeClearancesConfig: EndpointTestConfig<any, any> = {
  apiFunction: (params: any) => fetchWithZod(wsdot_bridge_clearances.getBridgeClearances, params),
  inputSchema: wsdot_bridge_clearances.getBridgeClearances.inputSchema,
  outputSchema: wsdot_bridge_clearances.getBridgeClearances.outputSchema,
  validParams: wsdot_bridge_clearances.getBridgeClearances.sampleParams || {},
  invalidParams: [
    {},
    { invalidField: "invalidValue" },
  ],
  endpointName: "getBridgeClearances",
  category: "data-retrieval",
  maxResponseTime: 120000,
  customTests: [
    {
      name: "Cache Strategy Validation",
      params: wsdot_bridge_clearances.getBridgeClearances.sampleParams || {},
      expectation: "success",
      description: "Validates that DAILY_STATIC caching works correctly",
    },
    {
      name: "Sample Parameters Test",
      params: wsdot_bridge_clearances.getBridgeClearances.sampleParams || {},
      expectation: "success",
      description: "Tests with the provided sample parameters",
    },
  ],
  endpointDefinition: wsdot_bridge_clearances.getBridgeClearances,
};

/**
 * Auto-generated test configuration for getBridgeClearancesByRoute endpoint
 */
export const getBridgeClearancesByRouteConfig: EndpointTestConfig<any, any> = {
  apiFunction: (params: any) => fetchWithZod(wsdot_bridge_clearances.getBridgeClearancesByRoute, params),
  inputSchema: wsdot_bridge_clearances.getBridgeClearancesByRoute.inputSchema,
  outputSchema: wsdot_bridge_clearances.getBridgeClearancesByRoute.outputSchema,
  validParams: wsdot_bridge_clearances.getBridgeClearancesByRoute.sampleParams || {},
  invalidParams: [
    {},
    { invalidField: "invalidValue" },
  ],
  endpointName: "getBridgeClearancesByRoute",
  category: "data-retrieval",
  maxResponseTime: 120000,
  customTests: [
    {
      name: "Cache Strategy Validation",
      params: wsdot_bridge_clearances.getBridgeClearancesByRoute.sampleParams || {},
      expectation: "success",
      description: "Validates that DAILY_STATIC caching works correctly",
    },
    {
      name: "Sample Parameters Test",
      params: wsdot_bridge_clearances.getBridgeClearancesByRoute.sampleParams || {},
      expectation: "success",
      description: "Tests with the provided sample parameters",
    },
  ],
  endpointDefinition: wsdot_bridge_clearances.getBridgeClearancesByRoute,
};

/**
 * All endpoint configurations for this API
 */
export const wsdot_bridge_clearancesConfigs = [
  getBridgeClearancesConfig,
  getBridgeClearancesByRouteConfig,
];

/**
 * API module configuration
 */
export const wsdot_bridge_clearancesModuleConfig = {
  moduleName: "Wsdot Bridge Clearances",
  endpoints: wsdot_bridge_clearancesConfigs,
  settings: {
    baseTimeout: 30000,
    requiresAuth: false,
    rateLimit: {
      requestsPerSecond: 10,
      burstLimit: 50,
    },
    testCategories: ["data-retrieval","validation","performance"],
  },
};
