/**
 * @fileoverview Auto-generated test configuration for Wsdot Border Crossings API
 *
 * This file is automatically generated from discovered Endpoint objects.
 * Do not edit manually - changes will be overwritten.
 */

import type { Endpoint } from "@/shared/endpoints";
import { fetchWithZod } from "@/shared/fetching";
import type { EndpointTestConfig } from "../generators/configGenerator";

// Import the actual endpoint definitions
import * as wsdot_border_crossings from "@/clients/wsdot-border-crossings";

/**
 * Auto-generated test configuration for getBorderCrossings endpoint
 */
export const getBorderCrossingsConfig: EndpointTestConfig<any, any> = {
  apiFunction: (params: any) => fetchWithZod(wsdot_border_crossings.getBorderCrossings, params),
  inputSchema: wsdot_border_crossings.getBorderCrossings.inputSchema,
  outputSchema: wsdot_border_crossings.getBorderCrossings.outputSchema,
  validParams: wsdot_border_crossings.getBorderCrossings.sampleParams || {},
  invalidParams: [
    {},
    { invalidField: "invalidValue" },
  ],
  endpointName: "getBorderCrossings",
  category: "data-retrieval",
  maxResponseTime: 10000,
  customTests: [
    {
      name: "Cache Strategy Validation",
      params: wsdot_border_crossings.getBorderCrossings.sampleParams || {},
      expectation: "success",
      description: "Validates that MINUTE_UPDATES caching works correctly",
    },
    {
      name: "Sample Parameters Test",
      params: wsdot_border_crossings.getBorderCrossings.sampleParams || {},
      expectation: "success",
      description: "Tests with the provided sample parameters",
    },
  ],
  endpointDefinition: wsdot_border_crossings.getBorderCrossings,
};

/**
 * All endpoint configurations for this API
 */
export const wsdot_border_crossingsConfigs = [
  getBorderCrossingsConfig,
];

/**
 * API module configuration
 */
export const wsdot_border_crossingsModuleConfig = {
  moduleName: "Wsdot Border Crossings",
  endpoints: wsdot_border_crossingsConfigs,
  settings: {
    baseTimeout: 30000,
    requiresAuth: false,
    rateLimit: {
      requestsPerSecond: 10,
      burstLimit: 50,
    },
    testCategories: ["data-retrieval","validation","performance"],
  },
};
