/**
 * @fileoverview Auto-generated test configuration for Wsdot Commercial Vehicle Restrictions API
 *
 * This file is automatically generated from discovered Endpoint objects.
 * Do not edit manually - changes will be overwritten.
 */

import type { Endpoint } from "@/shared/endpoints";
import { fetchWithZod } from "@/shared/fetching";
import type { EndpointTestConfig } from "../generators/configGenerator";

// Import the actual endpoint definitions
import * as wsdot_commercial_vehicle_restrictions from "@/clients/wsdot-commercial-vehicle-restrictions";

/**
 * Auto-generated test configuration for getCommercialVehicleRestrictions endpoint
 */
export const getCommercialVehicleRestrictionsConfig: EndpointTestConfig<any, any> = {
  apiFunction: (params: any) => fetchWithZod(wsdot_commercial_vehicle_restrictions.getCommercialVehicleRestrictions, params),
  inputSchema: wsdot_commercial_vehicle_restrictions.getCommercialVehicleRestrictions.inputSchema,
  outputSchema: wsdot_commercial_vehicle_restrictions.getCommercialVehicleRestrictions.outputSchema,
  validParams: wsdot_commercial_vehicle_restrictions.getCommercialVehicleRestrictions.sampleParams || {},
  invalidParams: [
    {},
    { invalidField: "invalidValue" },
  ],
  endpointName: "getCommercialVehicleRestrictions",
  category: "data-retrieval",
  maxResponseTime: 120000,
  customTests: [
    {
      name: "Cache Strategy Validation",
      params: wsdot_commercial_vehicle_restrictions.getCommercialVehicleRestrictions.sampleParams || {},
      expectation: "success",
      description: "Validates that DAILY_STATIC caching works correctly",
    },
    {
      name: "Sample Parameters Test",
      params: wsdot_commercial_vehicle_restrictions.getCommercialVehicleRestrictions.sampleParams || {},
      expectation: "success",
      description: "Tests with the provided sample parameters",
    },
  ],
  endpointDefinition: wsdot_commercial_vehicle_restrictions.getCommercialVehicleRestrictions,
};

/**
 * Auto-generated test configuration for getCommercialVehicleRestrictionsWithId endpoint
 */
export const getCommercialVehicleRestrictionsWithIdConfig: EndpointTestConfig<any, any> = {
  apiFunction: (params: any) => fetchWithZod(wsdot_commercial_vehicle_restrictions.getCommercialVehicleRestrictionsWithId, params),
  inputSchema: wsdot_commercial_vehicle_restrictions.getCommercialVehicleRestrictionsWithId.inputSchema,
  outputSchema: wsdot_commercial_vehicle_restrictions.getCommercialVehicleRestrictionsWithId.outputSchema,
  validParams: wsdot_commercial_vehicle_restrictions.getCommercialVehicleRestrictionsWithId.sampleParams || {},
  invalidParams: [
    {},
    { invalidField: "invalidValue" },
  ],
  endpointName: "getCommercialVehicleRestrictionsWithId",
  category: "data-retrieval",
  maxResponseTime: 120000,
  customTests: [
    {
      name: "Cache Strategy Validation",
      params: wsdot_commercial_vehicle_restrictions.getCommercialVehicleRestrictionsWithId.sampleParams || {},
      expectation: "success",
      description: "Validates that DAILY_STATIC caching works correctly",
    },
    {
      name: "Sample Parameters Test",
      params: wsdot_commercial_vehicle_restrictions.getCommercialVehicleRestrictionsWithId.sampleParams || {},
      expectation: "success",
      description: "Tests with the provided sample parameters",
    },
  ],
  endpointDefinition: wsdot_commercial_vehicle_restrictions.getCommercialVehicleRestrictionsWithId,
};

/**
 * All endpoint configurations for this API
 */
export const wsdot_commercial_vehicle_restrictionsConfigs = [
  getCommercialVehicleRestrictionsConfig,
  getCommercialVehicleRestrictionsWithIdConfig,
];

/**
 * API module configuration
 */
export const wsdot_commercial_vehicle_restrictionsModuleConfig = {
  moduleName: "Wsdot Commercial Vehicle Restrictions",
  endpoints: wsdot_commercial_vehicle_restrictionsConfigs,
  settings: {
    baseTimeout: 30000,
    requiresAuth: false,
    rateLimit: {
      requestsPerSecond: 10,
      burstLimit: 50,
    },
    testCategories: ["data-retrieval","validation","performance"],
  },
};
