/**
 * @fileoverview Auto-generated test configuration for Wsdot Mountain Pass Conditions API
 *
 * This file is automatically generated from discovered Endpoint objects.
 * Do not edit manually - changes will be overwritten.
 */

import type { Endpoint } from "@/shared/endpoints";
import { fetchWithZod } from "@/shared/fetching";
import type { EndpointTestConfig } from "../generators/configGenerator";

// Import the actual endpoint definitions
import * as wsdot_mountain_pass_conditions from "@/clients/wsdot-mountain-pass-conditions";

/**
 * Auto-generated test configuration for getMountainPassCondition endpoint
 */
export const getMountainPassConditionConfig: EndpointTestConfig<any, any> = {
  apiFunction: (params: any) => fetchWithZod(wsdot_mountain_pass_conditions.getMountainPassCondition, params),
  inputSchema: wsdot_mountain_pass_conditions.getMountainPassCondition.inputSchema,
  outputSchema: wsdot_mountain_pass_conditions.getMountainPassCondition.outputSchema,
  validParams: wsdot_mountain_pass_conditions.getMountainPassCondition.sampleParams || {},
  invalidParams: [
    {},
    { invalidField: "invalidValue" },
  ],
  endpointName: "getMountainPassCondition",
  category: "data-retrieval",
  maxResponseTime: 120000,
  customTests: [
    {
      name: "Cache Strategy Validation",
      params: wsdot_mountain_pass_conditions.getMountainPassCondition.sampleParams || {},
      expectation: "success",
      description: "Validates that DAILY_STATIC caching works correctly",
    },
    {
      name: "Sample Parameters Test",
      params: wsdot_mountain_pass_conditions.getMountainPassCondition.sampleParams || {},
      expectation: "success",
      description: "Tests with the provided sample parameters",
    },
  ],
  endpointDefinition: wsdot_mountain_pass_conditions.getMountainPassCondition,
};

/**
 * Auto-generated test configuration for getMountainPassConditions endpoint
 */
export const getMountainPassConditionsConfig: EndpointTestConfig<any, any> = {
  apiFunction: (params: any) => fetchWithZod(wsdot_mountain_pass_conditions.getMountainPassConditions, params),
  inputSchema: wsdot_mountain_pass_conditions.getMountainPassConditions.inputSchema,
  outputSchema: wsdot_mountain_pass_conditions.getMountainPassConditions.outputSchema,
  validParams: wsdot_mountain_pass_conditions.getMountainPassConditions.sampleParams || {},
  invalidParams: [
    {},
    { invalidField: "invalidValue" },
  ],
  endpointName: "getMountainPassConditions",
  category: "data-retrieval",
  maxResponseTime: 120000,
  customTests: [
    {
      name: "Cache Strategy Validation",
      params: wsdot_mountain_pass_conditions.getMountainPassConditions.sampleParams || {},
      expectation: "success",
      description: "Validates that DAILY_STATIC caching works correctly",
    },
    {
      name: "Sample Parameters Test",
      params: wsdot_mountain_pass_conditions.getMountainPassConditions.sampleParams || {},
      expectation: "success",
      description: "Tests with the provided sample parameters",
    },
  ],
  endpointDefinition: wsdot_mountain_pass_conditions.getMountainPassConditions,
};

/**
 * All endpoint configurations for this API
 */
export const wsdot_mountain_pass_conditionsConfigs = [
  getMountainPassConditionConfig,
  getMountainPassConditionsConfig,
];

/**
 * API module configuration
 */
export const wsdot_mountain_pass_conditionsModuleConfig = {
  moduleName: "Wsdot Mountain Pass Conditions",
  endpoints: wsdot_mountain_pass_conditionsConfigs,
  settings: {
    baseTimeout: 30000,
    requiresAuth: false,
    rateLimit: {
      requestsPerSecond: 10,
      burstLimit: 50,
    },
    testCategories: ["data-retrieval","validation","performance"],
  },
};
