/**
 * @fileoverview Auto-generated test configuration for Wsdot Weather Stations API
 *
 * This file is automatically generated from discovered Endpoint objects.
 * Do not edit manually - changes will be overwritten.
 */

import type { Endpoint } from "@/shared/endpoints";
import { fetchWithZod } from "@/shared/fetching";
import type { EndpointTestConfig } from "../generators/configGenerator";
import { z } from "zod";

// Import the actual endpoint definitions
import * as wsdot_weather_stations from "@/clients/wsdot-weather-stations";

/**
 * Auto-generated test configuration for getWeatherStations endpoint
 */
export const getWeatherStationsConfig: EndpointTestConfig<z.infer<typeof wsdot_weather_stations.getWeatherStations.inputSchema>, z.infer<typeof wsdot_weather_stations.getWeatherStations.outputSchema>> = {
  apiFunction: (params: z.infer<typeof wsdot_weather_stations.getWeatherStations.inputSchema>) => fetchWithZod(wsdot_weather_stations.getWeatherStations, params),
  inputSchema: wsdot_weather_stations.getWeatherStations.inputSchema,
  outputSchema: wsdot_weather_stations.getWeatherStations.outputSchema,
  validParams: wsdot_weather_stations.getWeatherStations.sampleParams || {},
  invalidParams: [
    {},
    { invalidField: "invalidValue" },
  ],
  endpointName: "getWeatherStations",
  category: "data-retrieval",
  maxResponseTime: 120000,
  customTests: [
    {
      name: "Cache Strategy Validation",
      params: wsdot_weather_stations.getWeatherStations.sampleParams || {},
      expectation: "success",
      description: "Validates that DAILY_STATIC caching works correctly",
    },
    {
      name: "Sample Parameters Test",
      params: wsdot_weather_stations.getWeatherStations.sampleParams || {},
      expectation: "success",
      description: "Tests with the provided sample parameters",
    },
  ],
  endpointDefinition: wsdot_weather_stations.getWeatherStations,
};

/**
 * All endpoint configurations for this API
 */
export const wsdot_weather_stationsConfigs = [
  getWeatherStationsConfig,
];

/**
 * API module configuration
 */
export const wsdot_weather_stationsModuleConfig = {
  moduleName: "Wsdot Weather Stations",
  endpoints: wsdot_weather_stationsConfigs,
  settings: {
    baseTimeout: 30000,
    requiresAuth: false,
    rateLimit: {
      requestsPerSecond: 10,
      burstLimit: 50,
    },
    testCategories: ["data-retrieval","validation","performance"],
  },
};
