name: Context7 Docs

on:
  release:
    types: [ published ]
  workflow_dispatch: {}

jobs:
  update-context7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # First-time registration (manual run only). Safe to keep; does nothing unless manually dispatched.
      - name: Add to Context7 (first run only)
        if: github.event_name == 'workflow_dispatch'
        uses: rennf93/upsert-context7@1.0
        with:
          operation: add
          library-name: "/RobJacobson/ws-dottie"

      # Refresh docs on every release tag
      - name: Refresh Context7 docs on release
        if: github.event_name == 'release'
        uses: rennf93/upsert-context7@1.0
        with:
          operation: refresh
          library-name: "/RobJacobson/ws-dottie"

      - name: Show result
        run: |
          echo "Success: ${{ steps.context7.outputs.success }}"
          echo "Status: ${{ steps.context7.outputs['status-code'] }}"
          echo "Message: ${{ steps.context7.outputs.message }}"

