name: Context7 Documentation Update

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  update-context7:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    # First-time registration (manual run only)
    - name: Add to Context7 (first run only)
      if: github.event_name == 'workflow_dispatch'
      uses: rennf93/upsert-context7@1.0
      with:
        operation: add
        library-name: "/RobJacobson/ws-dottie"
        api-key: ${{ secrets.CONTEXT7_API_KEY }}

    # Refresh docs on pushes to main branch and on releases
    - name: Refresh Context7 docs on main branch push
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: rennf93/upsert-context7@1.0
      with:
        operation: refresh
        library-name: "/RobJacobson/ws-dottie"
        api-key: ${{ secrets.CONTEXT7_API_KEY }}

    # Also refresh on releases
    - name: Refresh Context7 docs on release
      if: github.event_name == 'release'
      uses: rennf93/upsert-context7@1.0
      with:
        operation: refresh
        library-name: "/RobJacobson/ws-dottie"
        api-key: ${{ secrets.CONTEXT7_API_KEY }}