name: Context7 Docs

on:
  release:
    types: [ published ]
  workflow_dispatch: {}

jobs:
  update-context7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # First-time registration (manual run only). Safe to keep; does nothing unless manually dispatched.
      - name: Add to Context7 (first run only)
        if: github.event_name == 'workflow_dispatch'
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.CONTEXT7_API_KEY }}" \
            -d "{\"docsRepoUrl\":\"https://github.com/RobJacobson/ws-dottie\"}" \
            https://context7.com/api/v1/add

      # Refresh docs on every release tag
      - name: Refresh Context7 docs on release
        if: github.event_name == 'release'
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.CONTEXT7_API_KEY }}" \
            -d "{\"requestedLibrary\":\"/RobJacobson/ws-dottie\"}" \
            https://context7.com/refresh-library

      - name: Show result
        run: |
          echo "Context7 operation completed"

